repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-mock-methods
      - id: python-use-type-annotations
      - id: python-check-blanket-noqa
      - id: python-use-type-annotations
      - id: text-unicode-replacement-char
  - repo: local
    hooks:
        - id: flake8
          name: run flake8 in anfis package
          entry: bash -c "flake8 anfis/"
          language: python
          pass_filenames: false
          types: [ python ]
        - id: black
          name: run black in anfis package
          entry: bash -c "black anfis/"
          language: python
          pass_filenames: false
          types: [ python ]
        - id: mypy
          name: run mypy in anfis package
          entry: bash -c "mypy anfis/"
          language: python
          pass_filenames: false
          types: [ python ]
        - id: isort
          name: run isort in anfis package
          entry: bash -c "isort anfis/"
          language: python
          pass_filenames: false
          types: [ python ]
